### ISSUE TITLE
Syntax highlightning disappears in #+BEGIN_SRC when the top of the block is out of view

### ISSUE THREAD

**Issue by grigorievich** [redguardtoo/evil-nerd-commenter#100]
And one more thing : ) If the top of the block is not seen in the buffer, commenting will remove the syntax highlighting (everything in the block turns white). After scrolling back to the beginning of the block, everything comes back to color.

**Comment by redguardtoo** [comment]
The the top of the block should exist.

This package turn the snippet to its corresponding major mode (for example, python snippet to python-mode) temporarily  before commenting code. 

The problem is when restord `org-mode`, all trees are automatically collapsed. So I need go back to the parent node and expand its all children.

That's the reason why parent must exist.

**Comment by grigorievich** [comment]
> This package turn the snippet to its corresponding major mode (for example, python snippet to python-mode) temporarily before commenting code.

> The problem is when restord org-mode, all trees are automatically collapsed. So I need go back to the parent node and expand its all children.

I think both issues can be avoided by editing the src code in a seperate buffer and pasting the results back. Something like this:

```
  (defun my/comment-src-block ()
    (interactive)
    (let* ((p (point))
           (w (get-buffer-window (current-buffer))))
      (org-edit-src-code)
      (if (and (region-active-p) (> (cdr (bounds-of-thing-at-point 'line)) (region-end)))
          (set-window-point nil (1- (point))))
      (evilnc-comment-or-uncomment-lines 1)
      (org-edit-src-exit)
      (set-window-point w p)))
```

However this doesn't work for multiples lines well - the point jumps to the beginning of line. See bug report https://debbugs.gnu.org/cgi/bugreport.cgi?bug=bug%2334977
Hence the point jumping code - which doesn't work.

**Comment by redguardtoo** [comment]
Good idea, The org code was written ages ago. Maybe you can send me a pull request?

**Comment by grigorievich** [comment]
@redguardtoo will do, but first I better wait and see if the org-mode bug report will turn up any workarounds for the visual selection problem

**Comment by redguardtoo** [comment]
b71238d comment in org-src-block will not collapse node (Chen Bin)

**Comment by grigorievich** [comment]
@redguardtoo Thank you! 

If any of the bugs concerning multiline/visual commenting get resolved and if evilnc fixes will be required, I will let you know.

PS I will close the other issue as well.
