### ISSUE TITLE
Support c-style inner-line comment for rust-mode.

### ISSUE THREAD

**Issue by mookid** [redguardtoo/evil-nerd-commenter#101]
`evilnc-comment-or-uncomment-lines` states:

Case 3: If a region inside of ONE line is selected,
we comment/uncomment that region.
CORRECT comment syntax will be used for C++/Java/Javascript.

I suggest extending the syntax to rust, which also has the same comment syntax.

I am not super familiar with the code, but is there any reason not to make the list of supported major-modes 

```
(java-mode
 javascript-mode
 js-mode
 js2-mode
 js3-mode 
 rjsx-mode
 c++-mode
 objc-mode)
```  

from `evilnc--operation-on-lines-or-region` a customization option?

**Comment by redguardtoo** [comment]
OK, Could you give me some example? I'm not familiar with rust.

**Comment by mookid** [comment]
It is similar to C/C++/java style comment, except that `/* .. */` comments can be nested (`/* this is   /* a */ comment  */`).

See the grammar here: https://doc.rust-lang.org/reference/comments.html

**Comment by redguardtoo** [comment]
OK, I'm not sure how to handle nested comment. But c comment `/* */` is easy.

`js2-mode` inherits from `js-mode`, `rjsx-mode` inherits from `js2-mode`. `objc-mode` and `c++-mode` inherit from `cc-mode`. So you only need setup `js-mode` and `cc-mode` if it's generic feature.

I will support `rust-mode` asap.

**Comment by mookid** [comment]
Thanks! In my opinion, there is no need to care about nesting.

**Comment by redguardtoo** [comment]
a6d492b support inline comment for rust-mode (Chen Bin)

**Comment by mookid** [comment]
Thanks!
