### ISSUE TITLE
Cannot uncomment single-line Javascript comments

### ISSUE THREAD

**Issue by JediLuke** [redguardtoo/evil-nerd-commenter#102]
Version: 3.3.8 (package: 20190801.148)
Emacs Version: 27

when using `evilnc-comment-or-uncomment-lines` on a line with single-line comment, I see the following error in minibuffer "Can't find the comment end"

This was also happening in last version, I tried upgrading to see if it had been fixed.

Here's a snipped of the kinds of comments I'm talking about

```
// var audioPlayer    = document.querySelector('.green-audio-player');
```

The major mode is `HTML+JS`

**Comment by redguardtoo** [comment]
`C-h v major-mode`, what's the output?

**Comment by JediLuke** [comment]
A help buffer opens and I see this

```
Its value is ‘mhtml-mode’
Original value was fundamental-mode
Local in buffer demo_net.html.eex; global value is turn-on-evil-mode
```

That is in an Elixir eex file, but I have the same issue in a normal HTML file inside a HTML file inside a Javascript <script> tag. It inserts the correct comment, but can't uncomment it. This is what I see in that file

```
Its value is ‘js-mode’
Original value was fundamental-mode
Local in buffer foxamp.html; global value is turn-on-evil-mode
```

I doubt this matters but just for completeness, I have `C-h` bound to something else so I used `f1 v major-mode` which I am pretty sure is what you were after

**Comment by redguardtoo** [comment]
I can't reproduce the issue. It's possible you set the variable `comment-end` to `nil`.
It should be `""` in `mhtml-mode`.
