### ISSUE TITLE
Cannot comment vue buffer

### ISSUE THREAD

**Issue by jadestrong** [redguardtoo/evil-nerd-commenter#104]
```
        <el-radio-group v-model="form.fileType">
          <el-radio
            :label="0">CSV</el-radio>
          <el-radio
            :label="1">EXL</el-radio>
        </el-radio-group>
```
after comment
```
        <!-- <el-radio-group v-model="form.fileType"> -->
        <!-- <el-radio -->
        :label="/* 0">CSV</el-radio> */
        <!-- <el-radio -->
        :label="/* 1">EXL</el-radio> */
        <!-- </el-radio-group> -->
```
This is the warning message:

> defun web-mode-uncomment-vue-block NOT implemented in web-mode! Fix it or report to its maintainer.
Indenting region...done

Can it use web-mode's `web-mode-comment-or-uncomment`, this is function can work with vue buffer?

**Comment by jadestrong** [comment]
I tried to comment this line:
https://github.com/redguardtoo/evil-nerd-commenter/blob/00840b3da443ce48e9990d6badfa8f17b5e8baf9/evil-nerd-commenter.el#L460
Then it can works as expect,  but I'm not sure what it actually does.

**Comment by redguardtoo** [comment]
What's your major-mode? Any sample html to reproduce the issue?

**Comment by jadestrong** [comment]
I use doom-emacs's [g c] to comment ,  doom-emacs bind `evilnc-comment-operator` function to gc command now.

**Comment by jadestrong** [comment]
A vue file like this:
```
<template>
  <div class="hello">
    <h1>{{ msg }}</h1>
    <h3>Installed CLI Plugins</h3>
    <ul>
      <li><a href="#" target="_blank" rel="noopener">babel</a></li>
      <li><a href="#" target="_blank" rel="noopener">eslint</a></li>
    </ul>
  </div>
</template>

<script>
export default {
  name: 'HelloWorld',
  props: {
    msg: String
  }
}
</script>
```
When I marked the below three line to comment:
```
    <ul>
      <li><a href="#" target="_blank" rel="noopener">babel</a></li>
      <li><a href="#" target="_blank" rel="noopener">eslint</a></li>
```
execute ` M-x  evilnc-comment-or-uncomment-html-tag` , the result is 
```
    <!-- <ul>
      <li><a href="#" target="_blank" rel="noopener">babel</a></li>
      <li><a href="#" target="_blank" rel="noopener">eslint</a></li>
    </ul> -->
```

**Comment by redguardtoo** [comment]
a5555ff remove legacy code on old version of web-mode (Chen Bin)

**Comment by jadestrong** [comment]
It works, tks.
