### ISSUE TITLE
Cursor jumps when commenting in org _SRC block

### ISSUE THREAD

**Issue by dinkonin** [redguardtoo/evil-nerd-commenter#105]
When I use g c c to comment a line in an org mode SRC block the line gets commented BUT the cursor jumps to the end of the SRC block.

Emacs v26.3 (Linux) (Doom) , Org Version 9.4.

This advice written by @hlissner (Maintainer of doom emacs) fixes it.

```lisp
(defun fix-evilnc-in-org-blocks (orig-fn &rest args)
  (if (and (eq major-mode 'org-mode)
           (org-in-src-block-p t))
      (let ((point (point)))
        (prog1 (apply orig-fn args)
          (goto-char point)))
    (apply orig-fn args)))
(advice-add #'evilnc--working-on-region :around #'fix-evilnc-in-org-blocks)
```

**Comment by redguardtoo** [comment]
Thanks for the heads up. I will look into it.

**Comment by redguardtoo** [comment]
I assume you are using doom-emacs, right? Could you give detailed steps to reproduce the issue? I also need a sample org file.

**Comment by hlissner** [comment]
To clarify, I've recreated the issue in vanilla Emacs with the following:

```sh
mkdir ~/test
cd ~/test
git clone https://github.com/emacs-straight/org-mode
git clone https://github.com/emacs-evil/evil
git clone https://github.com/redguardtoo/evil-nerd-commenter
emacs -Q -L org-mode -L evil -L evil-nerd-commenter -l test.el
```

```elisp
;; in test.el
(require 'evil) ; latest commit
(require 'evil-nerd-commenter) ; latest commit
(require 'org) ; latest commit of org-plus-contrib

(evil-mode)

(evil-define-key '(visual normal) 'global "gc" #'evilnc-comment-operator)

(find-file "~/test.org")
(insert "* heading\n"
        "#+BEGIN_SRC elisp\n"
        "(progn 1)\n"
        "(progn 2)\n"
        "(progn 3)\n"
        "#+END_SRC\n")
```

Then move your cursor to line 2 of the src block (containing `(progn 2)`) and press `gcc`.

**Comment by dinkonin** [comment]
If it helps narrow things down, the issue is reproducible even without cloning the latest org-mode and using the built-in Org 9.1.9 in emacs 26.3,

**Comment by redguardtoo** [comment]
fixed. thanks.

**Comment by dinkonin** [comment]
The fix is working. Thank you all!
