### ISSUE TITLE
Comment until end of paragraph starts at cursor position instead of beginning of line

### ISSUE THREAD

**Issue by DerPhysikeR** [redguardtoo/evil-nerd-commenter#106]
Hi everybody, thank you for nerd-commenter!

I use spacemacs and frequently want to comment code until the end of the paragraph.
I do this with "g c }". Unfortunately, this key combination, while it is commenting until the end of the paragraph, starts commenting at the point position instead of the beginning of the line where the point currently is.
I assume this is not intended behaviour since "g c 2 j" doesn't do this.

Example python code (| is the point position):

```
foo| = 1
bar = 2
```

results in
```
foo|#  = 1
# bar = 2
```
instead of 

```
|# foo = 1
# bar = 2
```
which would be the case with "g c j".

The output of "evilnc-version" is 3.4.0.

**Comment by redguardtoo** [comment]
c9fa23e evil operator try to comment on whole lines if possible (Chen Bin)

**Comment by DerPhysikeR** [comment]
Wow that was fast.
Thank you!
