### ISSUE TITLE
Regression breaks line-wise commenting on inner forms

### ISSUE THREAD

**Issue by hlissner** [redguardtoo/evil-nerd-commenter#107]
https://github.com/redguardtoo/evil-nerd-commenter/commit/c9fa23ee7eba7e73fec1c35cd958eef5fa23585a introduced the following regression:

> Before https://github.com/redguardtoo/evil-nerd-commenter/commit/c9fa23ee7eba7e73fec1c35cd958eef5fa23585a

Assume `|` is the cursor position.

```elisp
(progn
  (|progn))
```

Pressing `gcab` results in:

```elisp
(progn
  |;; (progn)
  )
```

> After https://github.com/redguardtoo/evil-nerd-commenter/commit/c9fa23ee7eba7e73fec1c35cd958eef5fa23585a

```elisp
(progn
  (|progn))
```

Pressing `gcab` results in:

```elisp
(progn
  |;; (progn))
```

Causing an unbalanced `(`.

The first behavior seemed more intuitive and less destructive for lisps. This does not occur in non-lisp modes.

**Comment by redguardtoo** [comment]
I see, The easy solution is disable whole line expansion in  `emacs-lisp-mode`

**Comment by hlissner** [comment]
fa40dab appears to fix this issue. Thanks!
