### ISSUE TITLE
Comment start symbol is inserted twice in ESS R mode

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [redguardtoo/evil-nerd-commenter#110]
Hello,

Evil nerd commenter inserts `## ` (double hash) when commenting in ESS R mode.

Evil nerd commenter keeps inserting `## ` (double hash) even after the below configuration
```elisp
(add-hook 'ess-r-mode-hook
    (lambda () (setq comment-start "# " comment-end "")))
```
Evil nerd commenter inserts '-- ' (still double hyphen) when configured with the following configuration
```elisp
(add-hook 'ess-r-mode-hook
    (lambda () (setq comment-start "- " comment-end "")))
```
How the evil nerd commenter has to be configured to **insert a single hash** when commenting in ESS R mode?

**Comment by redguardtoo** [comment]
Could you give me some code sample of R? What's the major mode?

**Comment by volodymyrprokopyuk** [comment]
Hello,

Thank you for your support!

I use Emacs ESS R mode from https://ess.r-project.org/ with source code at https://github.com/emacs-ess/ESS

My ESS R mode configuration
```elisp
(add-to-list 'load-path "~/.emacs.d/ESS/lisp")
(autoload 'ess-r-mode "ess-r-mode" nil t)
(add-to-list 'auto-mode-alist '("\\.R\\'" . ess-r-mode))
```
My Evil nerd commenter configuration
```elisp
(add-to-list 'load-path "~/.emacs.d/evil-nerd-commenter")
(require 'evil-nerd-commenter)
(define-key evil-normal-state-map "gcc" 'evilnc-comment-or-uncomment-lines)
(define-key evil-normal-state-map "gc" 'evilnc-comment-operator)
```
A sample of R can be found at https://github.com/rstudio/shiny/blob/master/R/app.R

Thank you very much!

**Comment by redguardtoo** [comment]
has nothing to do with my code, 

See below code in `comment-region-default`,
```lisp
	(if (and (null arg) (not multi-char))
	    (setq numarg (* comment-add (if triple 2 1)))
	  (setq numarg (1- (prefix-numeric-value arg))))

	(comment-region-internal
	 beg end
	 (let ((s (comment-padright comment-start numarg)))
```

After reading emacs code, I think you can try set  `comment-add` to 0.

**Comment by volodymyrprokopyuk** [comment]
Hi,

The hash is still doubled when commenting after I've changed my ESS R mode configuration as below
```elisp
(add-to-list 'load-path "~/.emacs.d/ESS/lisp")
(autoload 'ess-r-mode "ess-r-mode" nil t)
(add-to-list 'auto-mode-alist '("\\.R\\'" . ess-r-mode))
(setq comment-add 0)
```
My knowledge of Emacs Lisp is limited. Could you please provide if possible the way to set the `comment-add` variable from the ESS R mode to 0?

Thank you!

**Comment by redguardtoo** [comment]
```lisp
(defun ess-mode-hook-setup ()
  (setq comment-add 0))
(add-hook 'ess-mode-hook 'ess-mode-hook-setup)
```
I'm not sure what's the `ess-r-mode`, I can only find `ess-mode`.

**Comment by volodymyrprokopyuk** [comment]
Hello,

Worked like a charm!

Thank you very much!
