### ISSUE TITLE
uncomment c style doc comments

### ISSUE THREAD

**Issue by condy0919** [redguardtoo/evil-nerd-commenter#112]
Performing `evilnc-comment-or-uncomment-lines` on the following comments

``` cpp
/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode(int x) : val(x), next(NULL) {}
 * };
 */
```

will produce

``` cpp
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode(int x) : val(x), next(NULL) {}
 * };
```

Installed `evil-nerd-commenter-20200417.59` from melpa

**Comment by redguardtoo** [comment]
I can give you a hook to remove extra stars.
This package only uses Emacs API `comment-region`. So comment style is set by major mode.

**Comment by redguardtoo** [comment]
can't reproduce the issue on Emacs 27. Maybe Emacs core fixed this problem.
