### ISSUE TITLE
[Error] Args out of range: 0, 0

### ISSUE THREAD

**Issue by ianpan870102** [redguardtoo/evil-nerd-commenter#115]
This error is very "niche". I tried my best to narrow it down a case where I can always reproduce -- and **finally** I found it!

## Error description and steps to reproduce
In **web-mode**, when commenting/uncommenting **the first line**, or if the selected region to comment/uncomment **contains the first line**, the expected behaviour will break and show "Args out of range: 0, 0" in the prompt below mode-line.

## Versions
I'm using the latest web-mode and also the latest stable Emacs (27.1). I'm on Ubuntu 20.04, if it matters.

**Comment by redguardtoo** [comment]
can't reproduce the issue with latest `web-mode` and `evil-nerd-commenter`.

Please prepare a minimum html file and give me specific steps to reproduce the issue.  Make sure you've run `M-x toggle-debug-on-error` first. Then send me the error message. I also need know `web-mode` version.

**Comment by ianpan870102** [comment]
Hi @redguardtoo. Upon further investigation, I found that HTML web-mode buffers are fine, but JS/JSX, TS/TSX or CSS buffers using web-mode as the major mode will trigger the error I described above.

I'm using web-mode version `20201009.1633`.

Here's a minimal CSS file for you to reproduce:

```css
.App {
  text-align: center;
}
```

## Steps to reproduce
- Place the cursor on the first line (for example, on the word `.App`. 
- Invoke `evilnc-comment-or-uncomment-lines`
- Observe that the first line is now commented to `/* .App { */`, the correct CSS-style comment.
- Invoke `evilnc-comment-or-uncomment-lines` on the first line again, attempting to uncomment the line.
- Observe that the command fails. In the echo area, we see "Args out of range: 0, 0".

With debug-on-error enabled, I captured the following backtrace:

![image](https://user-images.githubusercontent.com/36686900/96162224-dc1fcc00-0f4a-11eb-877e-b4aa7aaec49a.png)

```text
Debugger entered--Lisp error: (args-out-of-range 0 0)
  get-text-property(0 jsx-beg)
  web-mode-uncomment(1)
  web-mode-comment-or-uncomment()
  evilnc--web-mode-comment-or-uncomment(1 13)
  evilnc--comment-or-uncomment-region(1 13)
  (lambda (b e) (evilnc--fix-buggy-major-modes) (evilnc--comment-or-uncomment-region b e))(1 13)
  evilnc--operation-on-lines-or-region((lambda (b e) (evilnc--fix-buggy-major-modes) (evilnc--comment-or-uncomment-region b e)) 1)
  evilnc-comment-or-uncomment-lines(1)
  funcall-interactively(evilnc-comment-or-uncomment-lines 1)
  call-interactively(evilnc-comment-or-uncomment-lines nil nil)
  command-execute(evilnc-comment-or-uncomment-lines)
```

**Comment by redguardtoo** [comment]
This is `web-mode` bug, Stable version of `web-mode` is fine. Only latest version has this bug,

![image](https://user-images.githubusercontent.com/184553/96335660-e87c6400-10c5-11eb-8b0a-9d4762fd465d.png)

As you can see, I pass the right region beginning 1 to the web-mode api, but looks they forgot to consider the region beginning could be the first character of the buffer.

Please raise a bug to web-mode developers.

**Comment by ianpan870102** [comment]
@redguardtoo Thanks, just opened an issue there. Let me know if you want to keep this one open as well.

**Comment by ianpan870102** [comment]
Closed in this commit: https://github.com/fxbois/web-mode/commit/c10aab843e2c1747ca7789d0cad315c4f4802ab2
Tested and it works!
