### ISSUE TITLE
Use delimited comment /* ... */ insteam of line cooment -- when commenting region

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [redguardtoo/evil-nerd-commenter#117]
Hi,

Is it possible to configure the `evil-nerd-commenter` to use one style of comments when commenting lines and another style of comments when commenting regions of a specific file type?

**Example use case of commenting PostgreSQL files**
* On `gcc` (comment line) use `--` (SQL comment to the end of line)
* On `gc` on a visually selected region (comment region) use `/* ... */` instead of appending a new line to the end of the region and prepending the `--` to the beginning of the region which is current behavior

**Proposed strategy to line and region commenting**

* If there is only one comment style registered (e. g. `--`) for a file type, use the `--` for both line commenting and region commenting (currently implemented behavior by appending a new line at the end of the region)
* If there are two comment styles registered (e. g. `--` and `/* ... */` for a file type, use the `--` on line commenting and the `/* ... */`  on region commenting

**Rationale for the feature request**

It is very convenient, useful and productive to be able to comment out one parameter or a variable reference in a long line without introducing a line break (current behavior) in languages that support delimited comments `/* ... */` along with line comments `//`

**Comment by redguardtoo** [comment]
That's supported by Emacs since day one. `evil-nerd-commenter` only uses Emacs API `comment-region`. Check its documentation. You can set `comment-start`, `comment-end`. per file, per directory. 

See https://www.gnu.org/software/emacs/manual/html_node/elisp/Buffer_002dLocal-Variables.html

See https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.htm

You can also build your own command using this program's API.
```lisp
(defun my-comment-or-uncomment-lines (&optional num)
  "Comment or uncomment NUM lines."
  (interactive "p")
  (let* ((comment-start "aaa")
         (comment-end "bbb"))
    (evilnc-comment-or-uncomment-lines num)))
```

See https://www.gnu.org/software/emacs/manual/html_node/emacs/Options-for-Comments.html for more comment options.

**Comment by volodymyrprokopyuk** [comment]
By adding the below code both the line comments and the region comments become `/* ... */` (no more line comments `--`), which is fine for editing PostgreSQL.
```elisp
(add-hook 'sql-mode-hook
        #'(lambda () (setq comment-start "/*") (setq comment-end "*/")))
```
I can manage with this setup, but it would be nice to be able to declaratively define and distinguish between the line comments `--` and the region comments `/* ... */` as described in the initial proposal on the `evil-nerd-commenter` framework level.

**Comment by redguardtoo** [comment]
@volodymyrprokopyuk   Check `my-comment-or-uncomment-lines` in my previous comment. You can set `comment-start`, `comment-end` after checking `(region-active-p)`.

**Comment by volodymyrprokopyuk** [comment]
Hi,

When thinking about the solution I can identify the following actions to be performed in the `my-comment-or-uncomment-lines`
* if `(region-active-p)` then `(setq comment-start "/*") (setq comment-end "*/")`
* How do I connect the `my-comment-or-uncomment-lines` function to be like the current `evilnc-comment-or-uncomment-lines` and to work with the `evilnc-comment-operator`?
* How do I revert the comment marker back to `(setq comment-start "--") (setq comment-end "")` after the comment happened so the next time I can again take decision whether it is a line comment `--` or a region comment `/* ... */`?
* How do I attach the `my-comment-or-uncomment-lines` only to the specific mode (namely SQL mode)? I guess with a hook

My current setup of the `evil-nerd-commenter` is

```elisp
(defun config-evil-commenter ()
    (add-to-list 'load-path "~/.emacs.d/evil-nerd-commenter")
    (require 'evil-nerd-commenter)
    (define-key evil-normal-state-map "gcc" 'evilnc-comment-or-uncomment-lines)
    (define-key evil-normal-state-map "gc" 'evilnc-comment-operator))
```
I'm not very familiar with elisp. If it does not take you much time, could you please provide the `my-comment-or-uncomment-lines` function definition that implements the above logic and works well with my configuration setup (namely `gcc` and `gc`)?

Thank you very much in advance! Sorry if I ask too much. I the solution with reverting back `--` start to be convoluted we could leave it as is

**Comment by redguardtoo** [comment]
I add new variable `evilnc-comment-or-uncomment-region-function`.

See 8809dcc user can customize comment style (Chen Bin)

**Comment by volodymyrprokopyuk** [comment]
Thank you!
