### ISSUE TITLE
evil-copy-and-comment-operator does not copy in visual-mode

### ISSUE THREAD

**Issue by fredericgiquel** [redguardtoo/evil-nerd-commenter#118]
Hi,

In visual-mode, evil-copy-and-comment-operator comments (as evil-comment-operator) but does not copy the content visually selected.

# Steps to reproduce

To be sure that the problem is unrelated with my quite complex Emacs configuration, I launch Emacs with the following init.el file (`emacs -Q -l init.el`).

```emacs-lisp
;; Initialize package sources
(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))

;; Initialize use-package on non-Linux platforms
(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)

;; evil
(use-package evil
  :config
  (evil-mode))

;; evil-nerd-commenter
(use-package evil-nerd-commenter
  :after evil
  :config
  (evilnc-default-hotkeys))
```

For example, we can act in a paragraph level (but the problem seems to be independant of used text-object).

In normal-mode, I can copy and comment the whole paragraph with the following key sequence :
```
,.ip
```

But if I try to doom the same in visual-mode with
```
vip,.
```
the paragraph is only commented. The result is the same as with 
```
vip,,
```

**Comment by redguardtoo** [comment]
What command you are talking about? `evilnc-copy-and-comment-lines`?

**Comment by redguardtoo** [comment]
9c68f95 fixed: evil-copy-and-comment-operator does not copy in visual-mode (Chen Bin)

**Comment by fredericgiquel** [comment]
It works now as expected :+1:

Thank you
