### ISSUE TITLE
Feature Request: Copy and toggle comments in one operator

### ISSUE THREAD

**Issue by LoganBarnett** [redguardtoo/evil-nerd-commenter#120]
Hi! First, thank you so much for all the work you've done on this library which I probably use hundreds of times a day :)

I apologize if this is something vim/evil-mode handles quite well already: I'd like an operator in which I can both copy some text and toggle the comment state of that same text in one go.

Let's assume a fictional `gY` operator for this, and the buffer below:

``` sh
#!/usr/bin/env bash
echo 'hi'
```

If I place my cursor on the `echo` line, and do `gYy` (or `gYY`?), this is what my buffer would look like:
``` sh
#!/usr/bin/env bash
# echo 'hi'
```

And `echo 'hi'` would be in my yank ring (is that the Emacs term?). Doing `p` would then paste `echo 'hi'`.

The inverse would also hold true: If the text were commented, I'd have `# echo 'hi'` in my yank ring, and the text would be changed to `echo 'hi'`.

My reasoning for this request is that it is frequent that I want to comment something out, but copy + paste it first - sometimes I want to paste it elsewhere, so while `evilnc-command-and-kill-ring-save` and `evilnc-copy-and-comment-operator` come very close, they don't quite scratch the itch. If I have misunderstood the use of these functions (or missed another one), please correct me :)

I may be able to put together a pull request soon, but wanted to start with a ticket for the purposes of discussion, and to feel out if such a pull request is even desirable.

If it helps for reference (not comparison!), `evil-commentary` has a [evil-commentary-yank](https://github.com/linktohack/evil-commentary/blob/master/evil-commentary.el#L92) that does this. When I get a moment I'd like to try such an implementation with `evil-nerd-commenter`.

**Comment by redguardtoo** [comment]
b8ac35f add evilnc-yank-and-comment-operator (Chen Bin)

**Comment by LoganBarnett** [comment]
Tested this out locally and it works great! Thanks for both the implementation and the quick turnaround!

Closing the ticket.
