### ISSUE TITLE
cursor jumps when comment/uncommenting the region in org source block

### ISSUE THREAD

**Issue by hackmalife** [redguardtoo/evil-nerd-commenter#121]
It is similar to this issue https://github.com/redguardtoo/evil-nerd-commenter/issues/105
But problem still occurs to me.
In my case, I don't have any problem without region selected
The problem is when I select the region and then execute `evilnc-comment-or-uncomment-lines`. It jumps to the first line inside the block (a line below "+BEGIN_SRC")
I'm using Doom emacs version v27.2, and org-mode v9.5
Thanks.

**Comment by hackmalife** [comment]
I can use v instead of V to comment lines. problem remains same when I use V...I guess I should use v from now on.
Thanks

**Comment by redguardtoo** [comment]
sure. keep this issue open. `evilnc-guess-position-at-point` should return `line column` instead of buffer offset.

**Comment by redguardtoo** [comment]
It's fixed in latest commit.
