### ISSUE TITLE
evilnc-comment-or-uncomment-lines  has bug with major-mode `rjsx-mode` 

### ISSUE THREAD

**Issue by YUFENGWANG** [redguardtoo/evil-nerd-commenter#123]
for example

```js
// const str = 'http://localhost:3000'
```
when i invoke `evilnc-comment-or-uncomment-lines`, it results in 

```js 
const str = 'http:localhost:3000'
```
the `//` in `http://localhost:3000` get lost

after change major mode to `js2-mode` , it works correctly

**Comment by redguardtoo** [comment]
Try `(uncomment-region (line-beginning-position) (line-end-position))`.  You can reproduce the same issue.

Looks it's `rjsx-mode` bug, report the issue to its developer.

**Comment by YUFENGWANG** [comment]
Ok, i have submit a issue to `rjsx-mode`

**Comment by redguardtoo** [comment]
Another dirty workaround is use around advice to hacke `uncomment-region`. https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html
