### ISSUE TITLE
Do not uncomment already commented staff

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [redguardtoo/evil-nerd-commenter#129]
Hi,

Given the below line of JavaScript code
```js
const a = 1 // comment
```
When I comment the line with `g c c` the result is as follows
```js
// const a = 1 // comment
```
Then I uncomment the line with `g c c` and the result becomes
```js
const a = 1 comment
```
The initial `// comment` gets uncommented too which results in a syntax error.

I do not think that this should be the intended behavior. I'm using Doom Emacs.

Thank you!

**Comment by redguardtoo** [comment]
hat's exact command corresponding to `g c c`?

I tested both`evilnc-comment-operator` and `evilnc-comment-or-uncomment-lines`. Both are fine.

What's your major mode? I'm using `js2-mode`.

**Comment by volodymyrprokopyuk** [comment]
I'm using the out-of-the-box configuration of Doom Emacs for JavaScript. The major mode for JavaScript is [RJSX](https://github.com/felipeochoa/rjsx-mode). Switching to `js2-mode` solves the issue. I'm happy with the switch to `js2-mode` as I do not use JSX. Closing this issue for now. Thank you very much!
