### ISSUE TITLE
useage issue with vue file in web-mode

### ISSUE THREAD

**Issue by laampui** [redguardtoo/evil-nerd-commenter#130]
when in web-mode editing vue file, if I do `evilnc-comment-or-uncomment-lines` at the commented line, the consecutive comment lines will uncomment as well. It should just uncomment the line where the cursor at.

![录屏_emacs_20220717135938](https://user-images.githubusercontent.com/15785343/179386079-5516160f-b322-4eb0-8388-82622003f4d6.gif)

tested in `emacs -Q` with the following elisp snippet.
```el
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; To create a file, visit it with C-x C-f and enter text in its buffer.

(load "/home/laampui/.emacs.d/elpa/evil-nerd-commenter-20220524.1231/evil-nerd-commenter-autoloads.el")
(load "/home/laampui/.emacs.d/elpa/web-mode-20220615.602/web-mode-autoloads.el")

(require 'evil-nerd-commenter)
(require 'web-mode)

(evilnc-default-hotkeys)

(defun web-mode-hook-config ()
  (local-set-key (kbd "M-;") 'evilnc-comment-or-uncomment-lines))

(add-hook 'web-mode-hook 'web-mode-hook-config)

```

**Comment by redguardtoo** [comment]
I don't remember the details. The code was written ages ago. But looks it's a `web-mode` issue because  this package only calls web-mode api.

Try `(web-mode-comment-or-uncomment-region start end)`
