### ISSUE TITLE
how to set 'gc' as my comment operator?

### ISSUE THREAD

**Issue by bling** [redguardtoo/evil-nerd-commenter#15]
hello.  plugins like vim-commentary and tcomment use the `gc` as an operator.  so i can `gcc` to toggle a line, `gcG` to comment to the end of a file, or `gcp` to comment a paragraph, etc.

i tried adding `(setq evilnc-hotkey-comment-operator "gc")` to my `.emacs` but it's not working as expected.  a value of `"g c"` doesn't work either.

am i configuring it wrong or is this not supported?  thanks.

**Comment by justmytwospence** [comment]
I'm also having trouble with this. evil-mode is installed. I've tried this setq command before, after, and in stead of `(evilnc-default-hotkeys)`.  I just get undefined every time.

**Comment by redguardtoo** [comment]
@justmytwospence ,  `evil-comment-operator`  is an evil operator, so you need use evil way to assign a key for it. 

other commands are just normal emacs commands which using NOTHING from evil, so feel free to assign them any hotkey.

Check README about hotkey setup.

**Comment by justmytwospence** [comment]
Oh I see, thank you. That particular nuance is not actually in the README, from what I can see, but I guess its more of an evil-mode thing than an evilnc thing.

**Comment by redguardtoo** [comment]
check http://www.emacswiki.org/emacs/Evil  for how to define hotkey for operator.
