### ISSUE TITLE
Consider using \ as "leader" key instead of comma

### ISSUE THREAD

**Issue by danielwuz** [redguardtoo/evil-nerd-commenter#30]
May I suggest using backslash `\` as default leader key in `evilnc-hotkey-comment-operator` and `evilnc-default-hotkeys` instead of comma? 

I would really like to keep my evil mode the same with default vim key bindings as much as possible. I've also noticed that in vim, neither `vim-matchit` nor `nerdcommenter` would overwrite the normal `,` functionality by default. Maybe it's better not to use `,` as default leader key for their Emacs equivalence too?

Thanks for your time and patience to import such great modes into Emacs.

**Comment by srustamo** [comment]
I set `evilnc-hotkey-comment-operator` as per [1edf652](https://github.com/redguardtoo/evil-nerd-commenter/commit/1edf652fc61f22790493a071ec4397fc5178259a), however, this does not unbind the `, ,`.  This leads to the following problem: I want to set `,` in evil-mode by setting `(define-key evil-normal-state-map (kbd ",") 'evil-repeat-find-char-reverse)`. This works until restarting emacs, at which point I get the following error: `Warning (initialization): An error occurred while loading /Users/xxx/.emacs: error: Key sequence , , starts with non-prefix key ,`

**Comment by srustamo** [comment]
Setting `(setq evilnc-hotkey-comment-operator "\\")` before loading evil-nerd-commenter to get back the functionality of `,` as suggested by @siddhanathan works. Still, could you please consider unbinding `,` from in the source?

**Comment by redguardtoo** [comment]
`evilnc-hotkey-comment-operator` is only for text-object, I will update README.

**Comment by redguardtoo** [comment]
@srustamo, check 
 7a1647c donot use comma as default hotkey, v 1.5.14 (Chen Bin)

I tested with Emacs 24.4, it works.
