### ISSUE TITLE
evil-nerd-commenter + web-mode = :-(

### ISSUE THREAD

**Issue by bsandrow** [redguardtoo/evil-nerd-commenter#48]
Looks like `evil-nerd-commenter` is looking for `web-mode-is-comment`, which doesn't exist. In `web-mode`, you can hit `M-;` which [apparently](http://emacs.stackexchange.com/questions/7307/how-can-i-comment-a-block-of-css-or-html-in-web-mode) calls `comment-dwim`.

**Comment by redguardtoo** [comment]
already fixed  check latest commir

**Comment by bsandrow** [comment]
Thanks!
