### ISSUE TITLE
evilnc-invert-comment-line-by-line bug!

### ISSUE THREAD

**Issue by Dickby** [redguardtoo/evil-nerd-commenter#53]
Hi, I'm using your package for quite a while now and I like it a lot.
Today I tried the invert-line-by-line option for the first time and it doesn't work as expected.
Example:
if I type "evilnc-comment-operator j" , 3 instead of 2 lines are commented.
It seems like the wrong starting point of the evil-operator range is chosen.

Thanks for your work.

**Comment by redguardtoo** [comment]
I will look into this. I think other commands which don't use evil API should be fine. E

**Comment by redguardtoo** [comment]
@Dickby , it's EVIL's behavior I cannot override.

But as you see, other commands are not dependent on evil, so invert always works. I will update README to reflect this.

**Comment by Dickby** [comment]
Oh, I guess I have to use those other commands instead.
Thanks for your effort anyway.

**Comment by Dickby** [comment]
Hi, I got it working by just changing line 55 in evil-nerd-commenter-operator.el to:

    (evilnc--comment-or-uncomment-region beg (if evilnc-invert-comment-line-by-line
						 (- end 1)
					       end)))

**Comment by redguardtoo** [comment]
Thanks. 7e9bb32 invert comment bug when used with text object #53 (Chen Bin)

When dealing with lines you can use `evilnc-comment-or-uncomment-lines` instead, it's not dependent on evil mode and much more robust.

**Comment by Dickby** [comment]
Thanks!
