### ISSUE TITLE
Issue with org-indent-mode

### ISSUE THREAD

**Issue by Mrngilles** [redguardtoo/evil-nerd-commenter#54]
Hi,
Maybe you've encountered this issue before, but I looked everywhere and were not able to find any solution for this.
When I activate `org-indent-mode`, and I try and comment out code snippet in a file (this is my config file), the whole org-subtree opens up to the parent node, and all its children open.

If I have this:
```lisp
** Python configuration
#+begin_src emacs-lisp
(setq python-python-command "~/anaconda3/bin/ipython")
(setq py-shell-switch-buffers-on-execute-p t)
(setq py-switch-buffers-on-execute-p t)
(setq python-shell-virtualenv-path "~/anaconda3")
(when (executable-find "ipython")
  (setq python-shell-interpreter "ipython"))
#+end_src

** Anaconda config...
```

and try to comment a command, I will end up with: 
``` lisp
** Python configuration
#+begin_src emacs-lisp
(setq python-python-command "~/anaconda3/bin/ipython")
(setq py-shell-switch-buffers-on-execute-p t)
;; (setq py-switch-buffers-on-execute-p t)
(setq python-shell-virtualenv-path "~/anaconda3")
(when (executable-find "ipython")
  (setq python-shell-interpreter "ipython"))
#+end_src

** Anaconda config
#+begin_src emacs-lisp
(add-hook 'python-mode-hook 'anaconda-mode)
(setq python-shell-virtualenv-path "~/anaconda3")
#+end_src
```

I tried going through my config file, but were not able to find anything related. If you need more information, let me know.

**Comment by redguardtoo** [comment]
That's intentional, see `(outline-up-heading 1)` in the evil-nerd-commenter.el.

I go to the root node and re-expand everything inside that root node, everything else (for example, go up only one level and expand) makes the org display weird. 

I can't find any solution which will expand only current sub-mode and collapse all the other nodes,

**Comment by Mrngilles** [comment]
If I understand properly, the problem come from the fact that it changes the major mode and comes back to `org-mode`, which will collapse the nodes on startup.
Would it not be possible to:
- Open a hidden buffer in the desired mode
- Get `comment-start` and `comment-end` from the mode (as `local-com-start`, `local-com-end`)
- Kill the hidden buffer, unless not caching the start and end for the modes
- Comment in `org-mode` using the `local-com-start` and `local-com-end` var. I seem to have seen you can choose start and end delimiter in your commenting function.

Of course it makes you create a buffer, but I don't think it would be that problematic. You could even cache the comment delimiters to improve performance.

I'm no expert, but if you think this may be a good solution, let me know.

**Comment by redguardtoo** [comment]
eh, good idea, I picked up the simpler solution then, maybe I should study `org-edit-src-code`

**Comment by Mrngilles** [comment]
I'm trying some things, I'll also have a look at `org-edit-src-code`

**Comment by redguardtoo** [comment]
cool, patches are welcomed
