### ISSUE TITLE
Elixir Language Templating Commenting

### ISSUE THREAD

**Issue by Immortalin** [redguardtoo/evil-nerd-commenter#57]
When something like this:

``` EEx
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>
```

is commented, you get this:

``` EEx
<!-- <%= form_for @changeset, @action, fn f -> %> -->
<!--   <%= if @changeset.action do %> -->
<!--     <div class="alert alert-danger"> -->
<!--       <p>Oops, something went wrong! Please check the errors below:</p> -->
<!--       <ul> -->
<!--         <%= for {attr, message} <- f.errors do %> -->
<!--           <li><%= humanize(attr) %> <%= message %></li> -->
<!--         <% end %> -->
<!--       </ul> -->
<!--     </div> -->
<!--   <% end %> -->

<!--   <div class="form-group"> -->
<!--     <%= submit "Submit", class: "btn btn-primary" %> -->
<!--   </div> -->
<!-- <% end %> -->
```

However, it doesn't actually comment out the templating tags as they have to be turned to the [`<%# %>` ](http://elixir-lang.org/docs/v1.0/eex/) form.  One suggestion would be to keep the existing html style formatting as it helps the editor display things properly.

**Comment by redguardtoo** [comment]
what's your major-mode? web-mode?

**Comment by redguardtoo** [comment]
```lisp
(defalias 'web-mode-comment-elixir-block 'web-mode-comment-erb-block)
(defalias 'web-mode-uncomment-elixir-block 'web-mode-uncomment-erb-block)
```

**Comment by Immortalin** [comment]
@redguardtoo the problem is that elixir and EEx doesn't have any built-in block comments like ruby as most documentation is done via module attributes. Also, there are three types of tags:
```Elixir
Tags

EEx.SmartEngine supports the following tags:

<% Elixir expression - inline with output %>
<%= Elixir expression - replace with result %>
<%% EEx quotation - returns the contents inside %>
<%# Comments - they are discarded from source %>
```
This means implementing comments is not easy as you have to keep in memory what the previous type the tag was in before turning them into comments. An alternative would be to wrap the whole line withing a comment tag and remove them later when need. Sort of like a paredit slurp and barf. This might be easier as you could probably borrow some code from smartparens or paredit etc. However, I am not sure whether this would affect the compiler in anyway and whether it would escape the comments within comments etc. I am not sure whether the [elixir-vim](http://elixirsips.com/episodes/081_eex.html) or sublime text modules support commenting, maybe you can take a look at their source if they do.

**Comment by redguardtoo** [comment]
can you send me a a complete eex file?

**Comment by Immortalin** [comment]
@redguardtoo the code snippet in the first post is a complete eex file. It is merged and compiled at runtime into a complete html file.

**Comment by Immortalin** [comment]
@redguardtoo do I put the `defalias` in a web-mode hook or do I put it directly in my .emacs.d?

**Comment by redguardtoo** [comment]
I can see that, I will fix that this weekend

**Comment by Immortalin** [comment]
Thanks!

**Comment by redguardtoo** [comment]
770981c can comment/uncomment mixed code in web-mode (Chen Bin) v2.2

**Comment by Immortalin** [comment]
@redguardtoo thanks a ton! :D

**Comment by Immortalin** [comment]
@redguardtoo this fails for nested comments, e.g.:
```Elixir
  <script src="<%= static_path(@conn, "/js/en.js") %>"></script>
```

Commenting the above gives the following:

```Elixir
  <!-- <script src="<%= static_path(@conn, "/js/en.js") %>"></script> -->
```
The templating language in question is language agnostic i.e. it doesn't care whether you are using HTML, or YAML or JSON etc. it just does the templating.

**Comment by redguardtoo** [comment]
Just double check, so you want to only comment out the template language but keep the html, right?
That's doable. I can add a flag.

**Comment by Immortalin** [comment]
@redguardtoo actually, both. I am using `comment-or-uncomment-lines` but due to how the templating language parser works, it doesn't recognize the commented out HTML so there needs to be double commenting.

**Comment by redguardtoo** [comment]
got, interesting. I will see what I can do.

**Comment by redguardtoo** [comment]
upgrade to v2.3 then,
```lisp
(setq evilnc-comment-both-snippet-html t)
```

**Comment by Immortalin** [comment]
@redguardtoo thanks!

**Comment by Immortalin** [comment]
@redguardtoo and it also fails for multiple tags on one line e.g. 
```EEx
<li><%= humanize(attr) %> <%= message %></li>

```

**Comment by redguardtoo** [comment]
single line is fine, for the multiple line tag, I think it's doable but need more complicated algorithm. For now, even web-mode's own command `M-x web-mode-comment-or-uncomment` does not work.

**Comment by Immortalin** [comment]
@redguardtoo the single line fails when there's multiple EEx tags in-between the html tags

**Comment by redguardtoo** [comment]
Could you give me a sample file with multi-line and single line eex, and exact steps to reproduce the issue. and `M-x evilnc-version` to double check version.

**Comment by Immortalin** [comment]
@redguardtoo I am on 2.3 and the following is the example that fails:
```EEx
<li><%= humanize(attr) %> <%= message %></li>

```

**Comment by redguardtoo** [comment]
For multi-line snippet, the best way is do it in web-mode. I will raise a issue to web-mode developer.

For single line, it works on my computer, could you re-install evil-nerd-commenter?
![screencast](https://cloud.githubusercontent.com/assets/184553/12710015/231a1132-c906-11e5-8def-6ffd309a26f6.gif)
