### ISSUE TITLE
Test suite?

### ISSUE THREAD

**Issue by AdrieanKhisbe** [redguardtoo/evil-nerd-commenter#58]
Hello @redguardtoo 
Thanks for this great plugin :)

You mention in the README that you have tested it, but I don't see the test suite.
Was wondering where is it? (or do you do it by hand?)

> Tested on Emacs 23.4, 24.3, 24.4, 24.5

**Comment by redguardtoo** [comment]
Yes, by hand, for now.

**Comment by AdrieanKhisbe** [comment]
If you are interested into building a test suit you should give a look to [ecukes](https://github.com/ecukes/ecukes) and [ecukes](https://github.com/ecukes/espuds)
Cucumber tests for emacs. 

Otherwise with ert, here some exemple that could inspire you (https://github.com/chrisbarrett/swift-mode/blob/master/test/indentation-tests.el)

If wanna help to set up the Ci, have a look to [cask-package-toolset](https://github.com/AdrieanKhisbe/cask-package-toolset.el]. I can help you if you want. :smiley:
