### ISSUE TITLE
join comment lines?

### ISSUE THREAD

**Issue by blaenk** [redguardtoo/evil-nerd-commenter#60]
I found your [answer](http://emacs.stackexchange.com/a/10862/8941) to a question about joining comment lines and removing the comment delimiter. This is functionality I'm pretty sure I had in vim (via regular `J`, not a separate bind), though I can't remember for sure; perhaps it was some plugin I was using.

In any case, it's very useful functionality that I was surprised to not find in emacs or in any packages that I could find. You seemed to imply that you did it in this package, but I could find no mention of joining functionality.

Or were you simply referring to the method of detecting whether one was in a comment? If so, would you consider adding comment joining functionality to this package? It'd be nice if we could still use `J` and the comment-joining functionality would only kick-in if we were in a comment, otherwise it would delegate to the regular `J` evil functionality, instead of having to have yet another separate bind (although perhaps some people would like that as an option).

**Comment by redguardtoo** [comment]
interesting. I will considering it.

**Comment by blaenk** [comment]
I already created my own implementation, so feel free to close.
