### ISSUE TITLE
Help integrating matlab/octave-mode with evil-nerd-commenter?

### ISSUE THREAD

**Issue by mcandre** [redguardtoo/evil-nerd-commenter#62]
I love using evil-nerd-commenter to toggle the commented/uncommented state of blocks of code! However, when I try to do this in matlab-mode or octave-mode, it just inserts a new blank comment.

How can we tweak these modes to toggle commenting better?

**Comment by redguardtoo** [comment]
can you show me some sample? 

if you want to hack it by yourself, basically you just need check `evilnc--operation-on-lines-or-region` where we may re-define comment syntax, the actual comment operation happens in `evilnc--comment-or-uncomment-region` which is wrapper of `comment-or-uncomment-region`

So in essence it's simple, check the value of `comment-start`, `comment-end`, `comment-start-skip`, `comment-end-skip` and run `comment-or-uncomment-region` on selected region at first.

**Comment by redguardtoo** [comment]
my code is fine, you just need override major-mode's original keybinding.

Here is sample setup:
```lisp
(defun matlab-mode-hook-config ()
  (local-set-key (kbd "M-;") 'evilnc-comment-or-uncomment-lines))
(add-hook 'matlab-mode-hook 'matlab-mode-hook-config)
```

**Comment by mcandre** [comment]
Works for me, thanks!
