### ISSUE TITLE
Having problems with haml.... adds comments but does not remove them

### ISSUE THREAD

**Issue by staycreativedesign** [redguardtoo/evil-nerd-commenter#64]
http://www.screencast.com/t/3HLt5wES2GTa

**Comment by redguardtoo** [comment]
I'm not familiar with haml, but evil-nerd-commenter only use standard API.

In haml-mode, looks its implementation is not complete yet. haml-mode need defines `comment-start-skip` at minimum, or else Emacs API like `comment-only-p`, `forward-comment` won't work.

anyway, I workaround the issue in latest evil-nerd-commenter.el,
8e126cd workaround haml-mode comment issue (Chen Bin)
