### ISSUE TITLE
`evilnc-copy-and-comment-lines` doesn't copy anything

### ISSUE THREAD

**Issue by futuro** [redguardtoo/evil-nerd-commenter#66]
Hello,

`evilnc-copy-and-comment-lines` pastes your selection immediately below itself then comments out the selection, but it's not actually killing the text so nothing gets added to registers. Along with that, it's not made clear by the name of the function that it's going to immediately paste the text.

Can this instead put the text into the kill-ring or registers and then comment out the selection? My current test of this looks like the following.

``` elisp
  (defun evilnc-copy-and-comment-lines (&optional NUM)
    "Copy and comment NUM lines and comment out original lines.
NUM could be negative.

Case 1: If no region selected, operate on current line.
if NUM>1, comment/uncomment extra N-1 lines from next line

Case 2: Selected region is expanded to make it contain whole lines.
Then we operate the expanded region.  NUM is ignored."
    (interactive "p")
    ;; support negative number
    (when (< NUM 0)
      (forward-line (1+ NUM))
      (setq NUM (- 0 NUM)))

    (evilnc--operation-on-lines-or-region
     '(lambda (beg end)
        (evilnc--fix-buggy-major-modes)
        (evil-yank beg end)
        (comment-region beg end)
        )
     NUM))
```

Best,
Evan

**Comment by redguardtoo** [comment]
This feature is required by one of my user for modifying lines on production/staging server without version control software.

What's you use case?

**Comment by futuro** [comment]
I have code that I want to keep commented in it's original location, but I also want to paste it somewhere else, either in the file itself or in another file altogether. With the modifications above I can retain the original functionality by running `evilnc-copy-and-comment-lines` followed by a paste immediately afterwards. I could either wrap this up in an `evilnc-copypaste-and-comment-lines` function, or some other such thing.

**Comment by redguardtoo** [comment]
got, I can create an new command for you, could your suggest a proper name?

**Comment by redguardtoo** [comment]
54c618a add `evilnc-comment-and-kill-ring-save` (Chen Bin)
