### ISSUE TITLE
support the reverse direction comment

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [redguardtoo/evil-nerd-commenter#67]
something like to use C-u (-2) M-x `evilnc-comment-or-uncomment-lines` to comment two line above

**Comment by redguardtoo** [comment]
it's already there.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
but use the vim like keybinding just like (-2) <leader key> ci
anything will not happen

**Comment by redguardtoo** [comment]
it's because evil-numbers, I removed it now

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
it seem like to update the issue to the emacs.d
thank you for help
