### ISSUE TITLE
evil-called-interactively-p is deprecated

### ISSUE THREAD

**Issue by Somelauw** [redguardtoo/evil-nerd-commenter#71]
I have recently updated all my packages.

When using the evilnc-comment-operator, I now get the following error:

    evilnc-comment-operator: Symbol's function definition is void: evil-called-interactively-p

Maybe this function was removed and can be replaced by called-interactively-p

**Comment by Somelauw** [comment]
The function has just been re-added to evil, but now gives a deprecation warning. I'll change the title.

**Comment by redguardtoo** [comment]
thanks.

8b5830a remove obsolete macro, Emacs v23.2 is not my concern (Chen Bin)
