### ISSUE TITLE
Comment text object issues

### ISSUE THREAD

**Issue by duianto** [redguardtoo/evil-nerd-commenter#76]
There are some issues with the comment text object.

Tested in Windows 10 with Emacs 25.2.2.
The evil and evil-nerd-commenter packages were installed with Spacemacs.

`runemacs.exe --quick`
`M-x package-initialize`
`M-: (require 'evil)`
`M-x evil-mode`
`M-x evilnc-default-hotkeys`
`C-x b test`
`M-x emacs-lisp-mode`
copy this sample text:
```
;; a comment block
;; second line
;; third
```
paste the sample text into the `test` buffer
put the cursor on one of the comment lines
select the inner text object: `vic`

![selection-width-based-on-last-comment-line](https://user-images.githubusercontent.com/13420573/29568401-8a37f1f4-8750-11e7-9a05-258e042cf52c.png)

The selections width seems to be based on the length of the last comment.

#### 3 semicolons
If the first comment line has 3 semicolons, then the following comment lines first characters get excluded (I'm not sure how this could be handled):

![three-semicolons-on-first-line-excludes-first-chars-on-lines-below](https://user-images.githubusercontent.com/13420573/29568410-9426f73c-8750-11e7-8d4b-31976b763555.png)

#### selecting from an empty line above

If the cursor is on an empty line, above a single comment, and there's a command below that comment.
```

;; comment
(message "text")
```

When `vic` is pressed, then the selection extends to the left of the comment lines first character, and it also selects to the following command that isn't a comment:

![select-inner-comment-from-empty-line-above](https://user-images.githubusercontent.com/13420573/29568420-9f4b976c-8750-11e7-92a1-71b798663600.png)

If `vic` is pressed again, from this state, or if there's no active selection and the cursor is on a single line comment above a command, then the selection extends to the end of the command:

![non-comment-line-below-selected](https://user-images.githubusercontent.com/13420573/29568468-bbe24e7a-8750-11e7-84cc-725001b55c71.png)

#### outer comment
There's also a small issue with selecting the outer comment text object `vac` from an empty line above.

![select-outer-comment-from-empty-line-above](https://user-images.githubusercontent.com/13420573/29568483-c4a13e40-8750-11e7-920b-3baf917e7a40.png)

The empty line gets included with the comment.

**Comment by redguardtoo** [comment]
Solve the problem partially (require either the first or last line should be longest).

Look I need new API https://emacs.stackexchange.com/questions/12218/how-to-select-non-contiguous-regions-in-emacs

**Comment by duianto** [comment]
The fix needs some tweaking, when the first line is shorter, then the selection matches it's width:
![emacs_2017-08-28_18-59-40](https://user-images.githubusercontent.com/13420573/29786935-46d64aa0-8c2d-11e7-9891-98e8dfca9e37.png)

The cursor also ends up in the bottom left corner of the selection.
If it instead ended up in the bottom right corner, then maybe the `evil-end-of-line` command could be called. It extends the block selection to the end of every line.

This can be tested with the current behaviour like this:
with the cursor on some comments, select the inner comments `vic`
switch the cursor to the bottom right `O` (uppercase o)
and press `$` to call `evil-end-of-line`
![emacs_2017-08-28_20-38-23](https://user-images.githubusercontent.com/13420573/29787937-117c5c4c-8c31-11e7-88e8-c10d1e656adb.png)

**Comment by redguardtoo** [comment]
This is a little challenging, I'm still investigating.

**Comment by redguardtoo** [comment]
696d6fe select/yank text object of irregular lines (Chen Bin)
