### ISSUE TITLE
go to original column after evilnc-copy-and-comment-lines?

### ISSUE THREAD

**Issue by unhammer** [redguardtoo/evil-nerd-commenter#79]
If I do ` evilnc-copy-and-comment-lines`, the point invariable ends up at end-of-line. I typically want point at/near the column that it originally was at in the now-commented-line.

I currently do this instead
```
(defun my-evilnc-copy-and-comment-lines ()
             (interactive)
             (let ((c (current-column)))
               (call-interactively #'evilnc-copy-and-comment-lines)
               (move-to-column c)))
```
but maybe that should be built-in?

**Comment by redguardtoo** [comment]
76fd0c5 go to original column after copy and comment (Chen Bin)

**Comment by unhammer** [comment]
Oh great :-) Thanks!
