### ISSUE TITLE
commenting all buffer lines, doesn't comment the last char

### ISSUE THREAD

**Issue by duianto** [redguardtoo/evil-nerd-commenter#81]
### Description
The last character ends up on a newline below, when the buffers first and last lines are commented, with the `evilnc-comment-operator` command.

### Tested system
Windows 10 Version 1607 (OS Build 14393.1914)
GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-26
evil-nerd-commenter-20171106.1510
evil-20171129.651

### Steps to reproduce
Evil and Evil-nerd-commenter was installed with Spacemacs.
1. `runemacs.exe --quick`
2. on the Spacemacs master branch jump to step 4
3. on the develop branch, the packages are stored in a sub folder:
`.emacs.d/elpa/<emacs version>/develop/`:
update the path:
paste: `(setq package-user-dir "~/.emacs.d/elpa/26.0/develop/")`
(your version number may differ, check the elpa directory)
move the cursor to the end of the setq package-user-dir line and evaluate it `C-x C-e`.
4. `M-x package-initialize`
5. `M-: (require 'evil)`
6. `M-x evil-mode`
7. `M-x evilnc-default-hotkeys`
8. open a new buffer `C-x b` `test` `RET`
9. `M-x emacs-lisp-mode`
10. type `abc`
11. comment the line with `,,,` (3 commas)

#### Observed
The last character moves to the line below and remains uncommented:
```
;; ab
c
```
#### Expected
```
;; abc
```

### Multiple lines
It only happens when the buffers first and last lines are commented.
```
abc
def
ghi
```
With the cursor on the first line: `abc`
Press `2,,j` (2 comma comma j) to comment 2 lines down
#### Observed
```
;; abc
;; def
;; gh
i
```
#### Expected
```
;; abc
;; def
;; ghi
```

### Active region
The same thing happens when the buffers first and last lines are selected with `V` (uppercase).

#### The other selection modes work as expected
- `v` char
- `C-v` block
- `C-SPC` (which calls `set-mark-command`)
- `C-x SPC` (which calls `rectangle-mark-mode`)

### Notes
When the buffer has more than one line, and one selects less than all of the buffers lines, then it also works as expected.

**Comment by redguardtoo** [comment]
`C-h k ,,,`, I need know which command you are using.

**Comment by duianto** [comment]
>C-h k ,,, ENTER, I need know which command you are using.

`C-h k ,,` (two commas), shows:
```
, , runs the command evilnc-comment-operator (found in
evil-normal-state-map), which is an interactive Lisp function in
‘evil-nerd-commenter-operator.el’.

It is bound to , ,.

(evilnc-comment-operator BEG END &optional TYPE)

Comments text from BEG to END with TYPE.

[back]
```
There's no time to press the third comma and Enter.

But after pressing `,,` (without `C-h` first) to enter `evilnc-comment-operator` state (the cursor height seems to only show the bottom half, the same way as when one enters the evil `d` delete or `c` change operator state). In this state `C-h k ,` (one comma), shows:
```
, runs the command evil-line (found in evil-operator-shortcut-map),
which is an interactive compiled Lisp function in ‘evil-commands.el’.

It is bound to ,.

(evil-line &optional COUNT)

Move COUNT - 1 lines down.

[back]
```

It's not limited to triple comma. With two lines, one can press `,,j` (two commas and `j`), on the first line of:
```
abc
def
```
and see the same result:
```
;; abc
;; de
f
```

---

>Besides, what's result of C-u 3 evilnc-comment-or-uncomment-line?

With the cursor on the first line `abc`
```
abc
def
ghi
```
pressing: `C-u 3 M-x evilnc-comment-or-uncomment-lines` results in:
```
;; abc
;; def
;; ghi
```

**Comment by redguardtoo** [comment]
OK, now I understand. `,,` just comments text object `evil-mode` passed in. The actual text object is defined in `evil-mode`. Looks your evil version has some bug.

Please use stable version of `evil-mode`(current version is 1.2.13). I tested all the text objects and has no problem.

**Comment by duianto** [comment]
Are text objects used when there's an active region?
If not, and it uses `region-beginning` and `region-end` instead. Then it doesn't seem to be text-object related, because the issue only occurs with the `V` visual line selection type, but works fine with the other selection types.

I renamed my Spacemacs `.emacs.d` directory and `.spacemacs` file. And started over with just Emacs, and installed the stable melpa versions of:
```
evil-1.2.13
evil-leader-0.4.3
evil-nerd-commenter-3.1.2
```
but the issue occurs here as well.
```
;; ab
c
```
```
;; abc
;; def
;; gh
i
```

**Comment by duianto** [comment]
This might be the issue:

When there's a line selection:
https://github.com/redguardtoo/evil-nerd-commenter/blob/6a05c86bdf668fa2bb8a9daf76f3d7b241d7ba3d/evil-nerd-commenter-operator.el#L99-L100

Maybe the region end only should move back if it isn't on the last line, at the end of the buffer?

The same thing might be happening when there isn't an active region. Then the `evilnc-comment-operator`s `t` condition, calls `evilnc--extend-to-whole-comment`, which at first glance (I haven't looked into exactly what it does), might be doing something similar:
https://github.com/redguardtoo/evil-nerd-commenter/blob/6a05c86bdf668fa2bb8a9daf76f3d7b241d7ba3d/evil-nerd-commenter.el#L287-L288

**Comment by redguardtoo** [comment]
Thanks. 41d4370 Fixed: missing one char when comment end is (point-max) (Chen Bin)

**Comment by duianto** [comment]
Stable melpa already has the latest version version 3.1.3 so I just tried it and it's working fine, thanks.
