### ISSUE TITLE
comment selected block without the last line

### ISSUE THREAD

**Issue by it6** [redguardtoo/evil-nerd-commenter#85]
Thanks for this amazing package.

I hit `C-space` start a selection, select two lines and hit comment, I see comment also on my last line which has no selection.

![nerd-commenter](https://user-images.githubusercontent.com/5510191/37191605-b38520c0-232e-11e8-9c47-7a1fea8f225b.gif)

Is there any way to customize this when my point is on the last line and there is no selection I would like to see this behavior.

![regular](https://user-images.githubusercontent.com/5510191/37191646-ed60e0f4-232e-11e8-936b-0079a05bbbd9.gif)

this should only happen when there is no selection on the last line, if there is any selection on the last line (even a single character) I would like to see the first behavior where last line is commented too. 

This would be real helpful if you can provide a way to configure this or even consider it for default behavior, thanks.

**Comment by redguardtoo** [comment]
It you just want to comment two lines, you don't need select two FULL lines, the start point of could be any position of first line, and the end point could be any point of second line.

I'm not sure what command you are using from package, but I remember the original purpose of package is help you comment WHOLE line without selecting WHOLE line first.

**Comment by it6** [comment]
I am using `(evilnc-comment-or-uncomment-lines &optional NUM)`, the same thing happens when I start selection from bottom to top, see below.

![comment-from-bottom](https://user-images.githubusercontent.com/5510191/37236348-875b7872-23d4-11e8-9906-6a231b3c223c.gif)

I don't want to comment the third line since there is no selection made on the bottom(I just started from the third line). It is unintuitive behavior, I totally understand the ability to not select entire line and comment, but when there is no selection on a line it should not be commented. 

Please consider adding this as user config so when no selection is made on a line there will be no comment.

**Comment by redguardtoo** [comment]
Ok, you last screencast sees like a real bug. I will investigate and see what I can do.

**Comment by it6** [comment]
Please consider a solution for this.

**Comment by redguardtoo** [comment]
Sure. I am working on `counsel-etags` now. I will fix this issue tomorrow.

**Comment by it6** [comment]
Hello, any progress on this, thanks.

**Comment by redguardtoo** [comment]
I'm still working on `counsel-etags`, maybe look into it this weekend

**Comment by redguardtoo** [comment]
I tested with latest packages and watched your screencast again. Maybe I understand what happened.

You misunderstood a feature as a bug.

The line you cursor starts is always commented. In your case, the cursor starts or ends at the beginning of third line. So third line is commented out.

So you just need move cursort to the second line, press `C-SPC`, then move up one line. Now run the comment command. Please not you don't need select the whole first line and whole second line to comment these two lines.

The line cursor starts and the line cursor ends are always commented as if the whole line are selected. That's the feature of this command.

If you don't select any line at all and run `C-u 3 evilnc-comment-or-uncomment-lines `, three lines under cursor will be commented.
