### ISSUE TITLE
`evilnc-imenu-create-index-function` problem with old c style comment

### ISSUE THREAD

**Issue by Dickby** [redguardtoo/evil-nerd-commenter#86]
`evilnc-imenu-create-index-function`
cuts the first letters of the comment if comment style is set to `/* ... */` in c/c++-mode

**Comment by redguardtoo** [comment]
a22da65 better algorithm to extract comments in imenu (Chen Bin)

**Comment by redguardtoo** [comment]
34d4117 fixed issue when stripping trailing comment delimiter characters (Chen Bin)

**Comment by Dickby** [comment]
That is fixed too, thanks.
But:
1. comments shorter than 10 characters don't appear at all.
2. if there is no space between the comment closing */  and the last char of the comment, and the next line is a comment-line too, the two imenu entries are concatenated with an `\n` in between.
example:
/* first line comment*/
/* second line comment */
in counsel-imenu become
first line comment\nsecond line comment

**Comment by redguardtoo** [comment]
1. You can setup `evilnc-min-comment-length-for-imenu`
2. that's a feature. So you can search comment easily. For example, if you use ivy, you can use `first second` to search comment

**Comment by Dickby** [comment]
Thanks for the information, and for the fast fixes.
