### ISSUE TITLE
Can not comment react JSX automatically

### ISSUE THREAD

**Issue by ghost** [redguardtoo/evil-nerd-commenter#87]
As the title said, the result for comment is `//` instead of `{/**/}`
```
// error
const Demo = () =>
  <div>
    // <p>...</p>
  </div>

// correct
const Demo = () =>
  <div>
    {/* <p>...</p> */}
  </div>
```

**Comment by redguardtoo** [comment]
interesting question.

I think I need a more versatile solution for reactjs.

**Comment by redguardtoo** [comment]
Sorry to take so long to looking into this issue. Could you tell me what major mode you are using?

**Comment by yuanlai** [comment]
I use rjsx-mode with js2-mode.

**Comment by yuanlai** [comment]
Thanks to fix my issue, but it also seems buggy to use.

**Comment by yuanlai** [comment]
Hi, the `evilnc-comment-or-uncomment-paragraphs` is still have a problem on rjsx-mode.

**Comment by redguardtoo** [comment]
maybe i just add a new command to `evilnc-comment-or-uncomment-jsx-tags`?

**Comment by yuanlai** [comment]
If it is not adjust for jsx, expecting the this command work the same as in js2-mode.

**Comment by redguardtoo** [comment]
7b65a27 can comment or uncomment jsx tag (Chen Bin)

**Comment by redguardtoo** [comment]
It's in melpa now.

**Comment by yuanlai** [comment]
Sorry to disrupt again, the `evilnc-comment-or-uncomment-html-tag` is already not used on rjsx-mode, have any problem to your?

**Comment by redguardtoo** [comment]
Use `evilnc-comment-or-uncomment-html-tag` only. It can NOT be generic.

**Comment by yuanlai** [comment]
But this command just comment jsx only, my personal use the `paragraphs` much more.

**Comment by redguardtoo** [comment]
b5036f3 can comment html paragraphs (Chen Bin)

**Comment by redguardtoo** [comment]
you can download source code, run `./pkg.sh`, then `M-x package-install-file`, select the tar created by `pkg.sh`.

**Comment by yuanlai** [comment]
The paragraph function is also buggy to use...........

**Comment by redguardtoo** [comment]
place cursor on the open or closed tag when comment. Or else, please report details.

**Comment by yuanlai** [comment]
For example, the simple class component.
<img width="325" alt="2018-12-17 8 14 03" src="https://user-images.githubusercontent.com/10742934/50086748-f6969a80-0238-11e9-8c08-7fa8b674d36d.png">

When using `my-evilnc-comment-or-uncomment-paragraphs`, it weird form this result.
<img width="493" alt="2018-12-17 8 14 17" src="https://user-images.githubusercontent.com/10742934/50086761-fc8c7b80-0238-11e9-93d8-1c3b685ed91f.png">

**Comment by yuanlai** [comment]
The import line can be comment.

<img width="319" alt="2018-12-17 8 21 39" src="https://user-images.githubusercontent.com/10742934/50086859-5d1bb880-0239-11e9-9e89-e5e43cf40fb8.png">
<img width="339" alt="2018-12-17 8 21 53" src="https://user-images.githubusercontent.com/10742934/50086863-5ee57c00-0239-11e9-8c49-dc830ccaf820.png">

**Comment by redguardtoo** [comment]
There is empty line above and below paragraph. That's the definition.

**Comment by yuanlai** [comment]
How about considering to restore rjsx mode comment command to js2 mode?

**Comment by yuanlai** [comment]
Making these two mode as the same again?

**Comment by yuanlai** [comment]
You're right, I migrate to the specific command.

**Comment by redguardtoo** [comment]
I don't understand. All existing commands will use `//` by default. What's your requirement?

**Comment by yuanlai** [comment]
The default `evilnc-comment-or-uncomment-paragraphs` command is broken in rjsx-mode, so I want to have a alternative  to choice.

**Comment by redguardtoo** [comment]
`evilnc-comment-or-uncomment-paragraph` does not support jsx. Try use new command `evilnc-comment-or-uncomment-html-tag`. The reason is the old commands have too many dependency on existing Emacs APIs. It's not easy to extend them to support jsx.

**Comment by yuanlai** [comment]
Even not in jsx, this command is also not working, I have show many case below, so I want to report this error.

**Comment by redguardtoo** [comment]
`M-x evilnc-comment-or-uncomment-paragraph` will comment a paragraph wiht `//` in javascript file. 
A paragraph is a sequence of non-empty lines. My test looks fine.
