### ISSUE TITLE
Wrong comment action when using with evil-matchit

### ISSUE THREAD

**Issue by yanghaoxie** [redguardtoo/evil-nerd-commenter#93]
I will just give some examples to illustrate what I mean. (I use "|" to indicate cursor position， both examples are conducted in `emacs-lisp-mode`)

`example 1`
```
|((
 ))
```
I firstly run `evilnc-comment-operator`, then I run `evil-jump-item`, I will get
```
;; ((
;;   ))
```
This is the desired result.

`example 2`
```
|((
 ))
```
I firstly fun `evilnc-comment-operator`, then I run `evilmi-jump-items`, I will get
;; ((
;;   )
 )
You see, the last parenthesis is pushed out of the comment, which seems a wrong behaviour.

**Comment by redguardtoo** [comment]
interesting. I never thought combine both.

**Comment by yanghaoxie** [comment]
haha! I notice this because that I remap `evil-jump-item` to `evilmi-jump-items`.

I missed something, the examples are conducted in `emacs-lisp-mode`, I already edited my issue.

**Comment by redguardtoo** [comment]
904d9ee comment operator should be compatible with evil-matchit (Chen Bin)

**Comment by yanghaoxie** [comment]
I download the latest version, and load it using `use-package` keyword `load-path`, but the result was the same with `example 2`.

**Comment by redguardtoo** [comment]
I tested with v3.3.4 in `emacs-lisp-mode`. It works. I press ``,,@%` to comment `%` object.
Could you double check by `M-x evilnc-version`?

**Comment by yanghaoxie** [comment]
Sorry for reply after so many days, but the issue still exists.

I also test `evilmi-jump-items` with other `evil operator`, e.g., `d`, `y`, and `c`. And similar problem shows up, namely, those operation ignore the matching parentheses.

I guess this issue is  related to `evil-matchit`.

**Comment by redguardtoo** [comment]
I need more detail about "I firstly fun `evilnc-comment-operator`, then I run `evilmi-jump-items`," What exactly keys you pressed.

For `,,a%`, `%` is just shortcut of text object defined in `evil-matchit`. It's actually not `evilmi-jump-items`.

**Comment by yanghaoxie** [comment]
In order to eliminate the ambiguity, I actually try to execute all those `commands` from `Helm-M-x`.

I first press `"SPC-;"` which is bounded to `evilnc-comment-operator`, then I execute `evilmi-jump-items` from `Helm-M-x`.

**Comment by redguardtoo** [comment]
`M-x evilnc-comment-operator` then press `a%`. `%` is the text object short cut.

**Comment by yanghaoxie** [comment]
Oh! I see!

I checked `evil-matchit` a little bit, seems we are supposed to press `a` before `%` when we are using operator `v` or `d`, too. I guess I was confused by the advertising of `evil-matchit`: 

> No learning curve. Press “%” to jump. That’s all!

However, this behavior differs from `evil-jump-item`. Could you please explain a bit why an extra `a` is needed?

**Comment by redguardtoo** [comment]
Maybe you don't need press `a`, I just implemented `%` text object according to evil/vim specification. 
`i%` is the inner text object. `a%` is the object itself. The key bindings are decided by evil/vim.

**Comment by yanghaoxie** [comment]
It seems like that this strange behaviors are caused by following code: 
````(global-set-key [remap evil-jump-item] 'evilmi-jump-items)````
After I delete this, everything works fine.

**Comment by redguardtoo** [comment]
`,,%` comment out the text object `%` which has nothing to with `evilmi-jump-items`. The text object only  return a range object `(beg . end)` by executing `(evilmi--region-to-select-or-delete 1)`. Then the comment operator comment on that range. I can't reproduce the issue in `hello.el`.
