### ISSUE TITLE
Commenting broken - error: void-variable display-line-numbers-type

### ISSUE THREAD

**Issue by sebhahn** [redguardtoo/evil-nerd-commenter#96]
Recently I get the following error in spacemacs: error: void-variable display-line-numbers-type

see https://github.com/syl20bnr/spacemacs/issues/11995

**Comment by redguardtoo** [comment]
36304a6 tested in Emacs 24.4 (Chen Bin)

**Comment by sebhahn** [comment]
Thanks!
