### ISSUE TITLE
[org-mode] problem commenting inside #+BEGIN_SRC blocks

### ISSUE THREAD

**Issue by grigorievich** [redguardtoo/evil-nerd-commenter#97]
evilnc has been working well for me, but there is something wrong with src-code blocks.

if I try to comment the "function description" line (using evilnc-comment-or-uncomment-lines):

```
#+BEGIN_SRC python
  def f():
     function description 
  f()
#+END_SRC
```

then this comes out:

```
#+BEGIN_SRC python
  def f():
  #    function description 
  # f
  ()
#+END_SRC
```

Besides that, the point also jumps to the beginning of the block. Not sure if this happens only for me.

Any ideas?

**Comment by redguardtoo** [comment]
Yea, I can reproduce the issue. Let me have a look.

**Comment by redguardtoo** [comment]
d1a5c9c org v9.1 changed api to get language of src_block (Chen Bin)

**Comment by grigorievich** [comment]
@redguardtoo thank you for the quick fix, it works!
