### ISSUE TITLE
[org mode] Commenting inside #+BEGIN_SRC hides org headings

### ISSUE THREAD

**Issue by grigorievich** [redguardtoo/evil-nerd-commenter#99]
Hi! I am back with another snippet.

```
#+BEGIN_SRC python
moar code
#+END_SRC

* Heading 
text
```
-->
```
#+BEGIN_SRC python
# moar code
#+END_SRC

* Heading ...
```

Could you, please, verify?

I also get these trace messages:

> in the beginning ...
> org-back-to-heading: Before first headline at position 166 in buffer *scratch*

**Comment by redguardtoo** [comment]
Could you check the latest version?

**Comment by grigorievich** [comment]
@redguardtoo tested it, the org heading still collapses.

**Comment by redguardtoo** [comment]
The parent node must exist.

**Comment by grigorievich** [comment]
I think you might have not turned-on org-mode.

Steps to reproduce:
- start emacs
- open *scratch*
- M-x org-mode
- paste the following text
```
#+BEGIN_SRC python
line
#+END_SRC

* heading
subtext
```
- move to line in the src block and M-x evilnc-comment-or-uncomment-lines

Tested on this version:
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05
Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /usr/share/emacs/26.1/lisp/org/)

And the latest version:
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.7) of 2019-03-17
Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /usr/share/emacs/26.1/lisp/org/)
Evil version 1.2.13

**Comment by redguardtoo** [comment]
b71238d comment in org-src-block will not collapse node (Chen Bin)
